"""God LLM — perturbation generator (Phase 2).

Single LLM call, single JSON response: given a seed scenario + N, return
N distinct news events that could plausibly fire at a configured fork
round in the simulation. Each event becomes the ``injection_text`` for
one branch's Director Mode injection (via MiroShark's existing
``branch_counterfactual()`` API in Phase 3).

Output format (per-event):
    {
      "label": "blackrock_calming_statement",   # short slug for the branch
      "event_text": "BlackRock CEO Larry Fink ..." # passed verbatim to Director Mode
    }

The "round" field is configured in the scenario YAML (single fork round,
shared across all branches in v0) — not generated by the LLM.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import yaml
from openai import OpenAI


# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

PERTURBATION_PROMPT = """You are designing perturbations for an agent-based simulation. Each
perturbation has TWO parts that work together:

  - event_text: a plausible exogenous news event injected into all agents' feeds
                at the fork round. Provides public context for why the world has
                shifted.
  - mood_modifier: a private psychological disposition prepended to every agent's
                   persona. Each agent sees this as their own inner state and acts
                   consistently with it. THIS IS THE LOAD-BEARING PIECE — agents
                   ignore Director Mode events but reliably act on inner state.

Given the SEED SCENARIO below, generate exactly {n} distinct perturbation pairs.

REQUIREMENTS for the SET of {n} perturbations:

1. **Each pair is internally coherent.** The mood_modifier should align with the
   event_text — if the event is a stabilizing news flash, the mood should be calm;
   if the event is escalating, the mood should be alarmed. They reinforce each other.

2. **Distinct from each other.** No two perturbations should be variants of the
   same direction. Vary by:
     - directional pressure (stabilizing / escalating / ambiguous)
     - source actor of the event (different big actors)
     - mood register (calm / cautious / alarmed / euphoric / cynical / etc.)

3. **Span the outcome distribution.** Across the {n} pairs, include:
     - at least one strongly STABILIZING pair (event = bullish / mood = confident)
     - at least one strongly ESCALATING pair (event = bearish / mood = alarmed)
     - at least one AMBIGUOUS pair (event = mixed signals / mood = uncertain)

REQUIREMENTS for EACH event_text:

  - 2 to 4 sentences, factual news-flash tone, no editorializing.
  - Specific (named actors, concrete actions, specific dollar amounts).
  - Realistic (sourceable to a plausible actor with plausible motive — no
    deus ex machina).

REQUIREMENTS for EACH mood_modifier (this is the most important part):

  - 4 to 6 sentences in second person, addressing the agent directly as "you".
  - Includes ALL of: (a) the agent's current emotional state, (b) what action
    they have personally taken (or not taken) regarding USDC / the topic,
    (c) how they react when they see posts pushing the OPPOSITE direction,
    (d) what register they use when they write or comment.
  - Focused — pushes one specific psychological disposition, not a balanced view.
  - Behavioral, not topical — describes how agents feel/act, not what topic
    they discuss. E.g. "you are alarmed and have moved your USDC to USDT" works;
    "you are interested in stablecoin regulation" does not.

LABELS: short snake_case slugs. Used for filenames; not shown to agents.

SEED SCENARIO:
=== begin scenario ===
{seed_text}
=== end scenario ===

CONTEXT YOU CAN USE TO SHAPE PERTURBATIONS:
{context}

Output ONLY valid JSON in this exact shape (no markdown, no extra prose):
{{
  "perturbations": [
    {{
      "label": "<snake_case_slug>",
      "event_text": "<2-4 sentence news flash>",
      "mood_modifier": "<4-6 sentence inner-state paragraph in second person>"
    }},
    ...
  ]
}}
The "perturbations" array must have exactly {n} items.
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def _make_client() -> OpenAI:
    api_key = (os.environ.get("SMART_API_KEY")
               or os.environ.get("OPENAI_API_KEY"))
    base_url = (os.environ.get("SMART_BASE_URL")
                or os.environ.get("OPENAI_API_BASE_URL"))
    if not api_key:
        raise RuntimeError(
            "No API key found. Set SMART_API_KEY or OPENAI_API_KEY in the environment."
        )
    return OpenAI(api_key=api_key, base_url=base_url)


def _parse_json_response(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        parts = text.split("```")
        if len(parts) >= 2:
            inner = parts[1]
            if inner.lstrip().startswith("json"):
                inner = inner.split("\n", 1)[1] if "\n" in inner else inner[4:]
            text = inner.strip()
    return json.loads(text)


def _slugify(s: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", s.lower()).strip("_")
    return s[:60] if s else "unlabeled"


def generate_perturbations(
    seed_text: str,
    n: int,
    context: str = "",
    model: str | None = None,
    temperature: float = 0.7,
) -> list[dict]:
    """Call the God LLM once and return a list of N perturbation dicts.

    Args:
        seed_text: the seed scenario document text.
        n: number of distinct perturbations to generate.
        context: optional extra context (e.g., what's at stake, list of named actors).
        model: override model (defaults to SMART_MODEL_NAME or gemini-3.1-flash-lite-preview).
        temperature: sampling temperature. Default 0.7 for diversity (vs 0.0 for the
                     classifier — different goal here).

    Returns:
        list of {label, event_text} dicts, length == n.

    Raises:
        ValueError if the LLM returns malformed JSON or wrong-length list.
    """
    if n < 1:
        raise ValueError(f"n must be >= 1, got {n}")

    client = _make_client()
    chosen_model = (model
                    or os.environ.get("SMART_MODEL_NAME")
                    or "google/gemini-3.1-flash-lite-preview")

    prompt = PERTURBATION_PROMPT.format(
        n=n,
        seed_text=seed_text.strip(),
        context=context.strip() or "(no additional context provided)",
    )

    resp = client.chat.completions.create(
        model=chosen_model,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
    )
    raw = resp.choices[0].message.content
    parsed = _parse_json_response(raw)

    perturbations = parsed.get("perturbations")
    if not isinstance(perturbations, list):
        raise ValueError(f"Expected 'perturbations' list, got {type(perturbations).__name__}")
    if len(perturbations) != n:
        raise ValueError(
            f"Expected {n} perturbations, got {len(perturbations)}"
        )

    # Normalize + validate each item
    out = []
    for i, p in enumerate(perturbations):
        if not isinstance(p, dict):
            raise ValueError(f"perturbation {i} is not an object: {p!r}")
        label = _slugify(p.get("label") or f"branch_{i+1}")
        event_text = (p.get("event_text") or "").strip()
        mood_modifier = (p.get("mood_modifier") or "").strip()
        if not event_text:
            raise ValueError(f"perturbation {i} has empty event_text")
        item = {"label": label, "event_text": event_text}
        if mood_modifier:
            item["mood_modifier"] = mood_modifier
        out.append(item)

    # Distinctness sanity check: warn if any two event_texts are identical
    seen_events = set()
    seen_moods = set()
    for p in out:
        ek = p["event_text"][:200]
        if ek in seen_events:
            print(f"  warning: duplicate event_text detected: {ek[:80]}...",
                  file=sys.stderr)
        seen_events.add(ek)
        if "mood_modifier" in p:
            mk = p["mood_modifier"][:200]
            if mk in seen_moods:
                print(f"  warning: duplicate mood_modifier detected: {mk[:80]}...",
                      file=sys.stderr)
            seen_moods.add(mk)

    return out


# ---------------------------------------------------------------------------
# Scenario YAML loader (matches the format of usdc_depeg_scenario.yaml)
# ---------------------------------------------------------------------------

def load_scenario(path: str | Path) -> dict:
    """Load a scenario YAML and resolve the seed_document path relative to it."""
    path = Path(path)
    with open(path) as f:
        cfg = yaml.safe_load(f)

    seed_doc = cfg.get("seed_document")
    if seed_doc:
        seed_path = (path.parent / seed_doc).resolve()
        with open(seed_path) as f:
            cfg["_seed_text"] = f.read()
    else:
        cfg["_seed_text"] = ""

    return cfg


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _main():
    import argparse
    p = argparse.ArgumentParser(
        description="Generate N distinct perturbations for a scenario.",
    )
    p.add_argument("scenario", help="Path to a scenario YAML")
    p.add_argument("-n", "--num-branches", type=int, default=None,
                   help="Override N (default: from scenario.branching.num_branches)")
    p.add_argument("--model", default=None, help="Override LLM model")
    p.add_argument("--temperature", type=float, default=0.7)
    p.add_argument("--out", default=None,
                   help="Write perturbations to this JSON file (default: stdout)")
    args = p.parse_args()

    # Load env from common locations
    try:
        from dotenv import load_dotenv
        for env_path in [
            Path(__file__).parent.parent / ".env",
            Path("/Users/james/Documents/WorldFork/short/MiroShark/.env"),
        ]:
            if env_path.exists():
                load_dotenv(env_path)
                break
    except ImportError:
        pass

    cfg = load_scenario(args.scenario)
    branching = cfg.get("branching") or {}
    n = args.num_branches or branching.get("num_branches", 4)
    fork_round = branching.get("fork_round", 5)
    seed_text = cfg.get("_seed_text", "")

    # Optional context from the scenario
    context_parts = []
    if cfg.get("description"):
        context_parts.append(f"Scenario goal: {cfg['description']}")
    outcomes = cfg.get("outcomes") or []
    if outcomes:
        context_parts.append("Outcome variables being tracked:")
        for o in outcomes:
            context_parts.append(f"  - {o['name']}: {o['description']}")
    context_parts.append(
        f"\nThe perturbations will fire at simulation round {fork_round}."
    )
    context = "\n".join(context_parts)

    perturbations = generate_perturbations(
        seed_text=seed_text,
        n=n,
        context=context,
        model=args.model,
        temperature=args.temperature,
    )

    output = {
        "scenario": cfg.get("name", "unnamed"),
        "fork_round": fork_round,
        "n": n,
        "perturbations": perturbations,
    }

    text = json.dumps(output, indent=2, ensure_ascii=False)
    if args.out:
        Path(args.out).write_text(text)
        print(f"Wrote {len(perturbations)} perturbations → {args.out}")
    else:
        print(text)


if __name__ == "__main__":
    _main()
